hive_jdbc_pool:
  hive_jdbc_url: jdbc:hive2://10.2.39.67:10000
  hive.dbname: xxxxx
  hive_jdbc_username: hive
  hive_jdbc_password: hopson
    #配置初始化大小、最小、最大
  hive_initialSize: 20
  hive_minIdle: 20
  hive_maxActive: 500
    #配置获取连接等待超时的时间
  hive_maxWait: 60000

sendMail:
  hostName: smtp.exmail.qq.com #发送服务器的名字
  SSLOnConnect: true #是否启用SSL
  smtpPort: 465 #端口
  charset: UTF-8 #字符编码集
  addressTo: 779235932@qq.com,lv_ruichao@163.com #收件人地址
  addressFrom: 190654@lifeat.cn #发件人地址
  nameFrom: 数据中心 #发件人
  userName: 190654@lifeat.cn #发件人邮箱登录名
  passWord: Lrc123 #发件人邮箱登录密码
  subject: 无主题 #需用户传入，默认无主题


hive:
  tables: ods_customer_follow_part_day,ods_broker,ods_broker_auth,ods_broker_customer,ods_broker_customer_follow_status,ods_broker_customer_follow_status_remark,ods_brokerage_award_info,ods_brokerage_award_info_status,ods_brokerage_broker_apply,ods_brokerage_broker_apply_detail,ods_brokerage_company_apply,ods_brokerage_company_info,ods_brokerage_info,ods_commallot_initdata,ods_easylife_dealing_c_order,ods_easylife_developer_pay_amount,ods_easylife_developer_pay_amount_confirm,ods_easylife_developer_pay_amount_confirm_rel,ods_easylife_elimen_bill,ods_easylife_network_pusher_apply,ods_easylife_order,ods_easylife_order_brokerage_batch
  database: easylife_ods

file_path: dc_srv/src/main/resources/export/easylife_dw导出_2020-08-27.xlsx
queryMode: customQuery
