spring:
  application:
    name: init
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://121.225.24.224:8023/test?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://192.168.31.208:3306/test?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost/excel?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: wujian
    password: 1234
    druid:
      min-idle: 3
      max-active: 10
      validation-query: select 1
      test-while-idle: true
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 3600000
      connection-error-retry-attempts: 3

server:
  port: 8010
